# Generated by Django 5.0.6 on 2024-06-18 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я:")),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Вік:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис:')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Зображення:')),
            ],
            options={
                'verbose_name': 'Актори і режисери',
                'verbose_name_plural': 'Актори і режисери',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис:')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL:')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис:')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL:')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанри',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значення:')),
            ],
            options={
                'verbose_name': 'Зірка рейтингу',
                'verbose_name_plural': 'Зірки рейтингу',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид квитка:')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна квитка:')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Назва фільму:')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL:')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Обмеження у віці:')),
                ('year', models.DateField(default=django.utils.timezone.now, verbose_name='Дата виходу:')),
                ('video', models.FileField(upload_to='main_video', verbose_name='Трейлер фільму:')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Початок фільму:')),
                ('runtime', models.PositiveSmallIntegerField(default=0, help_text='Вказувати суму в гривнях:', verbose_name='Тривалість фільму:')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='main_img', verbose_name='Постер:')),
                ('img', models.ImageField(blank=True, null=True, upload_to='main_img', verbose_name="Прев'ю фільму:")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис фільму:')),
                ('country', models.CharField(max_length=100, verbose_name='Країна:')),
                ('movie_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Рейтинг фільму:')),
                ('world_premiere', models.DateField(default=django.utils.timezone.now, verbose_name="Світова прем'єра:")),
                ('budget', models.PositiveIntegerField(default=0, help_text='Вказувати суму в гривнях:', verbose_name='Бюджет:')),
                ('draft', models.BooleanField(default=False, verbose_name='Чорновик:')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='main.actor', verbose_name='Актор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_category', to='main.category', verbose_name='Категорія')),
                ('directors', models.ManyToManyField(related_name='film_director', to='main.actor', verbose_name='Режисер')),
                ('genre', models.ManyToManyField(related_name='film_genre', to='main.genre', verbose_name='Назва жанру:')),
                ('ticket', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_tikets', to='main.ticket', verbose_name='Квитки:')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок:')),
                ('description', models.TextField(verbose_name='Опис:')),
                ('image', models.ImageField(upload_to='movie_shots/', verbose_name='Зображення:')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='Фільм:')),
            ],
            options={
                'verbose_name': 'Кадр з фільма',
                'verbose_name_plural': 'Кадри з фільму',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP-адреса:')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.movie', verbose_name='Фільм:')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ratingstar', verbose_name='Зірка')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта:')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я:")),
                ('text', models.TextField(max_length=5000, verbose_name='Повідомлення')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='Фільм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reviews', verbose_name='Батько')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
    ]
